//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestSoapRestForms.wsServico {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8080/test", ConfigurationName="wsServico.TesteJavaEndpoint")]
    public interface TesteJavaEndpoint {
        
        [System.ServiceModel.OperationContractAttribute(Action="returnServico", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestSoapRestForms.wsServico.cadastroTo returnServico(string parametro1, string parametro2);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost:8080/test")]
    public partial class cadastroTo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long cadastroIdField;
        
        private bool cadastroIdFieldSpecified;
        
        private int quantidadeField;
        
        private bool quantidadeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long cadastroId {
            get {
                return this.cadastroIdField;
            }
            set {
                this.cadastroIdField = value;
                this.RaisePropertyChanged("cadastroId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cadastroIdSpecified {
            get {
                return this.cadastroIdFieldSpecified;
            }
            set {
                this.cadastroIdFieldSpecified = value;
                this.RaisePropertyChanged("cadastroIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantidadeSpecified {
            get {
                return this.quantidadeFieldSpecified;
            }
            set {
                this.quantidadeFieldSpecified = value;
                this.RaisePropertyChanged("quantidadeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TesteJavaEndpointChannel : TestSoapRestForms.wsServico.TesteJavaEndpoint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TesteJavaEndpointClient : System.ServiceModel.ClientBase<TestSoapRestForms.wsServico.TesteJavaEndpoint>, TestSoapRestForms.wsServico.TesteJavaEndpoint {
        
        public TesteJavaEndpointClient() {
        }
        
        public TesteJavaEndpointClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TesteJavaEndpointClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesteJavaEndpointClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TesteJavaEndpointClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestSoapRestForms.wsServico.cadastroTo returnServico(string parametro1, string parametro2) {
            return base.Channel.returnServico(parametro1, parametro2);
        }
    }
}
